#352 Change corretto version to install
Proemion/asdf-java pull request #5
Opened 2020-04-06 14:16 UTC by dawn-minion

Part of https://github.com/Proemion/psp-images/issues/352

2020-04-06 14:18 UTC, andrejserafim commented on bin/install
> +		8.242.08.1)
```suggestion
		corretto-8.242.08.1)
```

2020-04-06 14:18 UTC, andrejserafim commented on bin/list-all
> +echo "8.121 8.131 8.141 8.144 8.151 9.0.1 8.242.08.1"
```suggestion
echo "8.121 8.131 8.141 8.144 8.151 9.0.1 corretto-8.242.08.1"
```

2020-04-06 14:18 UTC, andrejserafim commented
@dawn-minion when looking at this today the prefix made it very clear

2020-04-06 14:21 UTC, unicolet requested changes
@dawn-minion I would recommend to add the new version alongside the old one. If you want we can remove all others, as we don't use them anyways (AFAIK)

2020-04-07 08:06 UTC, andrejserafim approved these changes
@dawn-minion thanks!@

2020-04-07 08:06 UTC, unicolet approved these changes
@dawn-minion perfect, thanks!

2020-04-07 08:07 UTC, merged